### ISSUE TITLE
Text_Translation/PingInfoView/PingInfoView_lng.ini  能否更新下最新版本的简体中文语言

### ISSUE THREAD

**Issue by xmbhsqktdqfpqdy** [HMBSbige/Text_Translation#1]
https://github.com/HMBSbige/Text_Translation/blob/master/PingInfoView/PingInfoView_lng.ini

http://www.nirsoft.net/utils/multiple_ping_tool.html
	PingInfoView 更新到 v1.65 ，多了很多选项，都是英文的

**Comment by HMBSbige** [comment]
这几天有空我更新下

**Comment by HMBSbige** [comment]
已更新！
