### ISSUE TITLE
取白名单的方式

### ISSUE THREAD

**Issue by ghost** [HMBSbige/Text_Translation#6]
我感觉这个项目：https://github.com/lbp0200/prc-sites 取白名单的方式不错。

**Comment by HMBSbige** [comment]
可以的，有空去试试

**Comment by HMBSbige** [comment]
5555
爬出来的列表太少了

**Comment by ghost** [comment]
作者不是爬了 400 多个吗，我测试了一下，各种常用的 CDN 都在里面。您爬了多少？
accelerated-domains.china.conf  和  gfwlist 里面的列表我随机测试了一部分，50%以上的域名其实不存在，感觉只增加不删除的。

**Comment by HMBSbige** [comment]
只增加不删除的是这样的
我爬了一堆错误，要不你把你爬的pr？

**Comment by ghost** [comment]
我不会啊，哈哈，作者那里有爬好的列表呀！

**Comment by HMBSbige** [comment]
OK，我再看看

**Comment by ghost** [comment]
用类似的方法再爬个黑名单就好了。

**Comment by HMBSbige** [comment]
只爬到231个，不知道为什么一堆错误
感觉不是很靠谱

我觉得还是 PAC 只判断国内 IP ，然后配合 [DNServer]()https://github.com/HMBSbige/DNServer 分流所有国内域名的解决方案更好

**Comment by ghost** [comment]
直接用他生成的列表代替 accelerated-domains.china.conf 生成一个效率更高的PAC。直接判断域名比判断IP应该更快吧？ accelerated-domains.china.conf 呢太多了，50%以上无效域名，剩下的90%以上其实也很少人用到，这些列表，可以说是为了满足1%的人付出的代价太高了。
用 DNSserver 又得多装一个软件哈。

**Comment by HMBSbige** [comment]
直接判断域名比判断IP应该更快？
我之前跟你说的感觉都白说了。。。
一直都是先判断域名再判断IP的

服务器多装一个服务端很麻烦吗？

用他生成的列表谁来维护

话说你完全可以自己替换啊 [GetCNDomainsAndIPv4](https://github.com/HMBSbige/GetCNDomainsAndIPv4)

我最近忙死了

**Comment by HMBSbige** [comment]
顺便说一下，我刚刚代替后测试了一下，连b站的视频都没法判断出国内，少了一堆cdn的域名
