### ISSUE TITLE
请问为什么本项目的chn_ip.txt大小大于其他项目所生成的

### ISSUE THREAD

**Issue by vocaloidchina** [HMBSbige/Text_Translation#7]
本项目的[chnip](https://github.com/HMBSbige/Text_Translation/blob/master/ShadowsocksR/chn_ip.txt)，相比起[另外一个](https://github.com/Tsuk1ko/SS-Collection/blob/master/SSR/chn_ip.txt)从17mon的项目中爬取的，多了大约有3000多行，究竟是什么造成这种差异的呢？我看两个项目更新时间都差不多。

谢谢

**Comment by HMBSbige** [comment]
Apnic
