### ISSUE TITLE
是否有计划继续维护SSR的user.rule

### ISSUE THREAD

**Issue by vocaloidchina** [HMBSbige/Text_Translation#8]
其他规则例如”绕过局域网“”绕过局域网和大陆“等规则都比较死板，而且也不支持域名的匹配，较为死板，因此使用user.rule可以有更大的自定义空间

**Comment by HMBSbige** [comment]
有其他项目维护了，自行搜索

**Comment by vocaloidchina** [comment]
@HMBSbige 搜了一下 维护的都是gfwlist 并没有针对其他规则的维护。
